server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://120.26.0.31:3306/splitmate?rewriteBatchedStatements=false
    username: root
    password: dJ<#/3-.1|7&m5ob
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: mySecret
  token-validity: 3600000
