server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/splitmate?rewriteBatchedStatements=false
    username: root
    password: dJ<#/3-.1|7&m5ob
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: splitemate.iota@gmail.com
    password: vzsjkztnrnvrmofz
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
minio:
  endpoint: http://minio:9000
  access-key: minio_root
  secret-key: minio_123456

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: mySecret
  token-validity: 3600000
